name: Run Jest testing suite

on:
  workflow_dispatch:
  pull_request:

jobs:
  testing:
    uses: ./.github/workflows/reusable/jest.yml
    with:
      package_manager: bun
      enable_summary: true
